# Currently not used in the Docker deployment.
local({
  options(timeout = 60*60*60)
})

install.packages("devtools")
library("devtools")

install_version("blastula", version = "0.3.2", repos = "https://cran.ma.imperial.ac.uk")
install_version("cowplot", version = "1.1.1", repos = "https://cran.ma.imperial.ac.uk")
install_version("gridExtra", version = "2.3", repos = "https://cran.ma.imperial.ac.uk")
install_version("lemon", version = "0.4.5", repos = "https://cran.ma.imperial.ac.uk")
install_version("mlr3misc", version = "0.6.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("mlr3fselect", version = "0.4.1", repos = "https://cran.ma.imperial.ac.uk")
install_version("mlr3proba", version = "0.2.6", repos = "https://cran.ma.imperial.ac.uk")
install_version("mlr3learners", version = "0.4.3", repos = "https://cran.ma.imperial.ac.uk")
install_version("mlr3", version = "0.9.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("polynom", version = "1.4-0", repos = "https://cran.ma.imperial.ac.uk")
install_version("data.table", version = "1.13.4", repos = "https://cran.ma.imperial.ac.uk")
install_version("lubridate", version = "1.7.9.2", repos = "https://cran.ma.imperial.ac.uk")
install_version("forcats", version = "0.5.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("stringr", version = "1.4.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("purrr", version = "0.3.4", repos = "https://cran.ma.imperial.ac.uk")
install_version("readr", version = "1.4.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("tidyr", version = "1.1.2", repos = "https://cran.ma.imperial.ac.uk")
install_version("tibble", version = "3.0.4", repos = "https://cran.ma.imperial.ac.uk")
install_version("ggplot2", version = "3.3.2", repos = "https://cran.ma.imperial.ac.uk")
install_version("tidyverse", version = "1.3.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("dplyr", version = "1.0.2", repos = "https://cran.ma.imperial.ac.uk")
install_version("DBI", version = "1.1.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("stats", version = "4.0.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("graphics", version = "4.0.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("grDevices", version = "4.0.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("utils", version = "4.0.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("datasets", version = "4.0.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("methods", version = "4.0.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("base", version = "4.0.0", repos = "https://cran.ma.imperial.ac.uk")
install_version("xgboost", version = "1.2.0.1", repos = "https://cran.ma.imperial.ac.uk")
